options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Angular App Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/projectmdanisulhaque/angular-app:latest',
      '-f', 'UI/SimpleBilling.web/Dockerfile',
      'UI/SimpleBilling.web'
    ]

  # Step 2: Build ASP.NET Core Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/projectmdanisulhaque/simplebilling:latest',
      '-f', 'SimpleBilling/SimpleBilling/Dockerfile',
      'API/SimpleBilling'
    ]
    dir: 'API/SimpleBilling'  # Set build context to the "API" folder

  # Step 3: Push Angular App Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projectmdanisulhaque/angular-app:latest']

  # Step 4: Push Backend Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projectmdanisulhaque/simplebilling:latest']

  # Step 5: Deploy Angular App to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/angular-app-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=simple-k8s-cluster'

  # Step 6: Deploy Backend Service to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/simplebilling-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=simple-k8s-cluster'

images:
  - 'gcr.io/projectmdanisulhaque/angular-app:latest'
  - 'gcr.io/projectmdanisulhaque/simplebilling:latest'
