version: '3.4'

services:
  angular-app:
    image: simplebilling.azurecr.io/angular-app:latest
    ports:
      - "7000:80"
    depends_on:
      - api
    networks:
      - backend

  api:
    image: simplebilling.azurecr.io/simplebilling:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__BillingDB=Server=db;Database=BillingDB;User Id=sa;Password=123+abc-456;TrustServerCertificate=True
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: simplebilling.azurecr.io/sql-server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123+abc-456
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - mssql-data:/var/opt/mssql

networks:
  backend:
    driver: bridge

volumes:
  mssql-data:
    driver: local
