version: '3.8'

services:
  angular-app:
    image: angular-app:latest
    build:
      context: ../../UI/SimpleBilling.web  # Path to the Angular project Dockerfile
      dockerfile: Dockerfile
    ports:
      - "7000:80"  # Expose Angular on port 7000
    depends_on:
      - simplebilling  # Ensure the backend starts first
    networks:
      - backend

  simplebilling:
    image: simplebilling:latest
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https-dev-cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=121
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BillingDB=Server=db;Database=BillingDB;User Id=sa;Password=123+abc-456;TrustServerCertificate=True
    ports:
      - "5000:8080"  # Map HTTP to internal 8080
      - "5001:8081"  # Map HTTPS to internal 8081
    volumes:
      - ./https-dev-cert.pfx:/https/https-dev-cert.pfx:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_TCP_PORT=1433
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123+abc-456
    ports:
      - "11433:1433"  # Expose SQL Server on port 11433
    networks:
      - backend
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "123+abc-456", "-Q", "SELECT 1"]
      interval: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true

networks:
  backend:
    driver: bridge  # Internal network for service communication

volumes:
  mssql-data:
    driver: local  # Persistent volume for SQL Server storage
