apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Single node can read/write
  resources:
    requests:
      storage: 3Gi  # Allocate 3GB storage
