apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebilling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplebilling
  template:
    metadata:
      labels:
        app: simplebilling
    spec:
      containers:
        - name: simplebilling
          image: gcr.io/projectmdanisulhaque/simplebilling:latest
          ports:
            - containerPort: 8080  # HTTP port
            - containerPort: 8081  # HTTPS port
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080;https://+:8081"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/https/https-dev-cert.pfx"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: "121"
            - name: ConnectionStrings__BillingDB
              value: "Server=mssql-service;Database=BillingDB;User Id=sa;Password=123+abc-456;TrustServerCertificate=True"
          volumeMounts:
            - name: https-cert
              mountPath: "/https"
              readOnly: true
      volumes:
        - name: https-cert
          secret:
            secretName: simplebilling-https-cert  # Secret containing the HTTPS certificate
---
apiVersion: v1
kind: Service
metadata:
  name: simplebilling-service
spec:
  type: LoadBalancer
  selector:
    app: simplebilling
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
