name: Deploy to Google Cloud

on:
  push:
    branches:
      - google-cloud  # Trigger the workflow on pushes to the google-cloud branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud authentication
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          project_id: projectmdanisulhaque

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Google Artifact Registry
      - name: Log in to Google Artifact Registry
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://europe-west3-docker.pkg.dev
        continue-on-error: true  # Allow the workflow to continue even if the login fails, to gather more information

      # Debugging: Check if docker login was successful
      - name: Check Docker login status
        run: |
          docker info
        if: failure()  # This step runs only if the previous login step fails

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker build -t europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/angular-app:latest -f UI/SimpleBilling.web/Dockerfile .
          docker build -t europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/simplebilling:latest -f backend/Dockerfile .
          docker build -t europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/db:latest -f db/Dockerfile .
          docker push europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/angular-app:latest
          docker push europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/simplebilling:latest
          docker push europe-west3-docker.pkg.dev/projectmdanisulhaque/simplebilling-docker-repo/db:latest

      # Set up Kubernetes configuration and deploy to GKE
      - name: Set up Kubernetes and deploy to GKE
        run: |
          # Authenticate with GKE cluster
          gcloud container clusters get-credentials simplebilling-cluster --zone europe-west3 --project projectmdanisulhaque
          
          # Apply Kubernetes deployment configuration
          kubectl apply -f k8s/deployment.yaml
